@baseUrl = https://checked-api.herokuapp.com/api/

### @name createUser
POST {{baseUrl}}users/create HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=bigMeme
&password=bigMeme


### @name login
POST {{baseUrl}}users/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=bigMeme
&password=bigMeme


### @name getZonesByUser
GET {{baseUrl}}zones/users/1 HTTP/1.1
Content-Type: application/x-www-form-urlencoded 


### @name triggerAssembly
GET {{baseUrl}}assembly/0 HTTP/1.1
Content-Type: application/x-www-form-urlencoded 

### @name linkUserWithMember
POST {{baseUrl}}links/create HTTP/1.1
Content-Type: application/x-www-form-urlencoded

userId=1
&memberId=7
&relationship=Parent

### @name getLinksByMember
GET {{baseUrl}}links/members/7 HTTP/1.1
Content-Type: application/x-www-form-urlencoded 

### @name updateUserSettings
POST {{baseUrl}}settings/update/2 HTTP/1.1
Content-Type: application/x-www-form-urlencoded

{
    "darkMode": false,
    "interval": 100,
    "maxTemperature": 20,
    "minTemperature": 10,
    "gatheringThreshold": 1
}